spring:
  datasource:
    url: jdbc:postgresql://ct250-ttdat-cloud.h.aivencloud.com:23952/ct250?sslmode=require
    username: avnadmin
    password: AVNS_AgrUvRlC9rufFI_x5al
#    url: jdbc:postgresql://localhost:5432/ct250
#    username: postgres
#    password: 123456

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  data:
    web:
      pageable:
        one-indexed-parameters: true
application:
  security:
    rsa:
      rsa-public-key: classpath:certs/public-key.pem
      rsa-private-key: classpath:certs/private-key.pem
    jwt:
      access-token-validity-in-seconds: 604800 # 1 days
      refresh-token-validity-in-seconds: 604800 #7 days