spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://ct250-davika-airways.l.aivencloud.com:24893/ct250?sslmode=require}
    username: ${DATABASE_USER:avnadmin}
    password: ${DATABASE_PASSWORD:AVNS_RtkjrmnXf9d8sxZHkz1}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  servlet:
    multipart:
      enabled: true


  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:""}
    elasticsearch:
      repositories:
        enabled: true

  batch:
    job:
      enabled: false #prevents any batch job from running automatically at startup

  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: UTF-8
    username: davikaairways1109@gmail.com
    password: zfxjbsfmcwpcebte
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


#  elasticsearch:
#    uris: ${ELASTICSEARCH_URL:http://localhost:9200}
  main:
    allow-bean-definition-overriding: true


management:
  health:
    elasticsearch:
      enabled: false


application:
  security:
    rsa:
      rsa-public-key: classpath:certs/public-key.pem
      rsa-private-key: classpath:certs/private-key.pem
    jwt:
      access-token-validity-in-seconds: 604800 # 1 days
      refresh-token-validity-in-seconds: 604800 #7 days


cloudinary:
  url: ${CLOUDINARY_URL:cloudinary://146776767144144:S28Z_bYDWnTZCpfrgMHwJw2k4cw@dq9aigkgv}


payment:
  vnPay:
    url: ${PAY_URL}
    tmnCode: ${TMN_CODE}
    secretKey: ${SECRET_KEY}
    returnUrl: ${RETURN_URL}
    version: ${VERSION}
    command: ${COMMAND}
    orderType: ${ORDER_TYPE}


