spring:
  datasource:
  #  url: jdbc:postgresql://ct250-ttdat-cloud.h.aivencloud.com:23952/ct250?sslmode=require
#    username: avnadmin
#    password: AVNS_AgrUvRlC9rufFI_x5al
    url: jdbc:postgresql://localhost:5432/ct250
    username: user
    password: pass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
application:
  security:
    jwt:
      base64-secret: iUPAlAIfmBbdXzZmlrhAJMPGQlcc5RoXc/42g8YsW38PXlBFAN7tTSVHgOCWW+7l0vT/NYPWYv3C0BQukGLAVg==
      token-validity-in-seconds: 86400 #1 day
#      refresh-token:
#        expiration: 604800000 #7 days