-- COUNTRY
insert into public.countries (country_code, country_name, iso2_code, iso3_code)
values (93, 'Afghanistan', 'AF', 'AFG'),
       (355, 'Albania', 'AL', 'ALB'),
       (213, 'Algeria', 'DZ', 'DZA'),
       (1684, 'American Samoa', 'AS', 'ASM'),
       (376, 'Andorra', 'AD', 'AND'),
       (244, 'Angola', 'AO', 'AGO'),
       (1264, 'Anguilla', 'AI', 'AIA'),
       (672, 'Antarctica', 'AQ', 'ATA'),
       (1268, 'Antigua and Barbuda', 'AG', 'ATG'),
       (54, 'Argentina', 'AR', 'ARG'),
       (374, 'Armenia', 'AM', 'ARM'),
       (297, 'Aruba', 'AW', 'ABW'),
       (61, 'Australia', 'AU', 'AUS'),
       (43, 'Austria', 'AT', 'AUT'),
       (994, 'Azerbaijan', 'AZ', 'AZE'),
       (1242, 'Bahamas', 'BS', 'BHS'),
       (973, 'Bahrain', 'BH', 'BHR'),
       (880, 'Bangladesh', 'BD', 'BGD'),
       (1246, 'Barbados', 'BB', 'BRB'),
       (375, 'Belarus', 'BY', 'BLR'),
       (32, 'Belgium', 'BE', 'BEL'),
       (501, 'Belize', 'BZ', 'BLZ'),
       (229, 'Benin', 'BJ', 'BEN'),
       (1441, 'Bermuda', 'BM', 'BMU'),
       (975, 'Bhutan', 'BT', 'BTN'),
       (591, 'Bolivia', 'BO', 'BOL'),
       (387, 'Bosnia and Herzegovina', 'BA', 'BIH'),
       (267, 'Botswana', 'BW', 'BWA'),
       (55, 'Brazil', 'BR', 'BRA'),
       (246, 'British Indian Ocean Territory', 'IO', 'IOT'),
       (1284, 'British Virgin Islands', 'VG', 'VGB'),
       (673, 'Brunei', 'BN', 'BRN'),
       (359, 'Bulgaria', 'BG', 'BGR'),
       (226, 'Burkina Faso', 'BF', 'BFA'),
       (257, 'Burundi', 'BI', 'BDI'),
       (855, 'Cambodia', 'KH', 'KHM'),
       (237, 'Cameroon', 'CM', 'CMR'),
       (1, 'Canada', 'CA', 'CAN'),
       (238, 'Cape Verde', 'CV', 'CPV'),
       (1345, 'Cayman Islands', 'KY', 'CYM'),
       (236, 'Central African Republic', 'CF', 'CAF'),
       (235, 'Chad', 'TD', 'TCD'),
       (56, 'Chile', 'CL', 'CHL'),
       (86, 'China', 'CX', 'CHN'),
       (61, 'Christmas Island', null, 'CXR'),
       (61, 'Cocos Islands', 'CC', 'CCK'),
       (57, 'Colombia', 'CO', 'COL'),
       (269, 'Comoros', 'KM', 'COM'),
       (682, 'Cook Islands', 'CK', 'COK'),
       (506, 'Costa Rica', 'CR', 'CRI'),
       (385, 'Croatia', 'HR', 'HRV'),
       (53, 'Cuba', 'CU', 'CUB'),
       (599, 'Curacao', 'CW', 'CUW'),
       (357, 'Cyprus', 'CY', 'CYP'),
       (420, 'Czech Republic', 'CZ', 'CZE'),
       (243, 'Democratic Republic of the Congo', 'CD', 'COD'),
       (45, 'Denmark', 'DK', 'DNK'),
       (253, 'Djibouti', 'DJ', 'DJI'),
       (1767, 'Dominica', 'DM', 'DMA'),
       (1809, 'Dominican Republic', 'DO', 'DOM'),
       (670, 'East Timor', 'TL', 'TLS'),
       (593, 'Ecuador', 'EC', 'ECU'),
       (20, 'Egypt', 'EG', 'EGY'),
       (503, 'El Salvador', 'SV', 'SLV'),
       (240, 'Equatorial Guinea', 'GQ', 'GNQ'),
       (291, 'Eritrea', 'ER', 'ERI'),
       (372, 'Estonia', 'EE', 'EST'),
       (251, 'Ethiopia', 'ET', 'ETH'),
       (500, 'Falkland Islands', 'FK', 'FLK'),
       (298, 'Faroe Islands', 'FO', 'FRO'),
       (679, 'Fiji', 'FJ', 'FJI'),
       (358, 'Finland', 'FI', 'FIN'),
       (33, 'France', 'FR', 'FRA'),
       (689, 'French Polynesia', 'PF', 'PYF'),
       (241, 'Gabon', 'GA', 'GAB'),
       (220, 'Gambia', 'GM', 'GMB'),
       (995, 'Georgia', 'GE', 'GEO'),
       (49, 'Germany', 'DE', 'DEU'),
       (233, 'Ghana', 'GH', 'GHA'),
       (350, 'Gibraltar', 'GI', 'GIB'),
       (30, 'Greece', 'GR', 'GRC'),
       (299, 'Greenland', 'GL', 'GRL'),
       (1473, 'Grenada', 'GD', 'GRD'),
       (1671, 'Guam', 'GU', 'GUM'),
       (502, 'Guatemala', 'GT', 'GTM'),
       (441481, 'Guernsey', 'GG', 'GGY'),
       (224, 'Guinea', 'GN', 'GIN'),
       (245, 'Guinea-Bissau', 'GW', 'GNB'),
       (592, 'Guyana', 'GY', 'GUY'),
       (509, 'Haiti', 'HT', 'HTI'),
       (504, 'Honduras', 'HN', 'HND'),
       (852, 'Hong Kong', 'HK', 'HKG'),
       (36, 'Hungary', 'HU', 'HUN'),
       (354, 'Iceland', 'IS', 'ISL'),
       (91, 'India', 'IN', 'IND'),
       (62, 'Indonesia', 'ID', 'IDN'),
       (98, 'Iran', 'IR', 'IRN'),
       (964, 'Iraq', 'IQ', 'IRQ'),
       (353, 'Ireland', 'IE', 'IRL'),
       (441624, 'Isle of Man', 'IM', 'IMN'),
       (972, 'Israel', 'IL', 'ISR'),
       (39, 'Italy', 'IT', 'ITA'),
       (225, 'Ivory Coast', 'CI', 'CIV'),
       (1876, 'Jamaica', 'JM', 'JAM'),
       (81, 'Japan', 'JP', 'JPN'),
       (441534, 'Jersey', 'JE', 'JEY'),
       (962, 'Jordan', 'JO', 'JOR'),
       (7, 'Kazakhstan', 'KZ', 'KAZ'),
       (254, 'Kenya', 'KE', 'KEN'),
       (686, 'Kiribati', 'KI', 'KIR'),
       (383, 'Kosovo', 'XK', 'XKX'),
       (965, 'Kuwait', 'KW', 'KWT'),
       (996, 'Kyrgyzstan', 'KG', 'KGZ'),
       (856, 'Laos', 'LA', 'LAO'),
       (371, 'Latvia', 'LV', 'LVA'),
       (961, 'Lebanon', 'LB', 'LBN'),
       (266, 'Lesotho', 'LS', 'LSO'),
       (231, 'Liberia', 'LR', 'LBR'),
       (218, 'Libya', 'LY', 'LBY'),
       (423, 'Liechtenstein', 'LI', 'LIE'),
       (370, 'Lithuania', 'LT', 'LTU'),
       (352, 'Luxembourg', 'LU', 'LUX'),
       (853, 'Macau', 'MO', 'MAC'),
       (389, 'Macedonia', 'MK', 'MKD'),
       (261, 'Madagascar', 'MG', 'MDG'),
       (265, 'Malawi', 'MW', 'MWI'),
       (60, 'Malaysia', 'MY', 'MYS'),
       (960, 'Maldives', 'MV', 'MDV'),
       (223, 'Mali', 'ML', 'MLI'),
       (356, 'Malta', 'MT', 'MLT'),
       (692, 'Marshall Islands', 'MH', 'MHL'),
       (222, 'Mauritania', 'MR', 'MRT'),
       (230, 'Mauritius', 'MU', 'MUS'),
       (262, 'Mayotte', 'YT', 'MYT'),
       (52, 'Mexico', 'MX', 'MEX'),
       (691, 'Micronesia', 'FM', 'FSM'),
       (373, 'Moldova', 'MD', 'MDA'),
       (377, 'Monaco', 'MC', 'MCO'),
       (976, 'Mongolia', 'MN', 'MNG'),
       (382, 'Montenegro', 'ME', 'MNE'),
       (1664, 'Montserrat', 'MS', 'MSR'),
       (212, 'Morocco', 'MA', 'MAR'),
       (258, 'Mozambique', 'MZ', 'MOZ'),
       (95, 'Myanmar', 'MM', 'MMR'),
       (264, 'Namibia', 'NA', 'NAM'),
       (674, 'Nauru', 'NR', 'NRU'),
       (977, 'Nepal', 'NP', 'NPL'),
       (31, 'Netherlands', 'NL', 'NLD'),
       (599, 'Netherlands Antilles', 'AN', 'ANT'),
       (687, 'New Caledonia', 'NC', 'NCL'),
       (64, 'New Zealand', 'NZ', 'NZL'),
       (505, 'Nicaragua', 'NI', 'NIC'),
       (227, 'Niger', 'NE', 'NER'),
       (234, 'Nigeria', 'NG', 'NGA'),
       (683, 'Niue', 'NU', 'NIU'),
       (850, 'North Korea', 'KP', 'PRK'),
       (1670, 'Northern Mariana Islands', 'MP', 'MNP'),
       (47, 'Norway', 'NO', 'NOR'),
       (968, 'Oman', 'OM', 'OMN'),
       (92, 'Pakistan', 'PK', 'PAK'),
       (680, 'Palau', 'PW', 'PLW'),
       (970, 'Palestine', 'PS', 'PSE'),
       (507, 'Panama', 'PA', 'PAN'),
       (675, 'Papua New Guinea', 'PG', 'PNG'),
       (595, 'Paraguay', 'PY', 'PRY'),
       (51, 'Peru', 'PE', 'PER'),
       (63, 'Philippines', 'PH', 'PHL'),
       (64, 'Pitcairn', 'PN', 'PCN'),
       (48, 'Poland', 'PL', 'POL'),
       (351, 'Portugal', 'PT', 'PRT'),
       (1787, 'Puerto Rico', 'PR', 'PRI'),
       (974, 'Qatar', 'QA', 'QAT'),
       (242, 'Republic of the Congo', 'CG', 'COG'),
       (262, 'Reunion', 'RE', 'REU'),
       (40, 'Romania', 'RO', 'ROU'),
       (7, 'Russia', 'RU', 'RUS'),
       (250, 'Rwanda', 'RW', 'RWA'),
       (590, 'Saint Barthelemy', 'BL', 'BLM'),
       (290, 'Saint Helena', 'SH', 'SHN'),
       (1869, 'Saint Kitts and Nevis', 'KN', 'KNA'),
       (1758, 'Saint Lucia', 'LC', 'LCA'),
       (590, 'Saint Martin', 'MF', 'MAF'),
       (508, 'Saint Pierre and Miquelon', 'PM', 'SPM'),
       (1784, 'Saint Vincent and the Grenadines', 'VC', 'VCT'),
       (685, 'Samoa', 'WS', 'WSM'),
       (378, 'San Marino', 'SM', 'SMR'),
       (239, 'Sao Tome and Principe', 'ST', 'STP'),
       (966, 'Saudi Arabia', 'SA', 'SAU'),
       (221, 'Senegal', 'SN', 'SEN'),
       (381, 'Serbia', 'RS', 'SRB'),
       (248, 'Seychelles', 'SC', 'SYC'),
       (232, 'Sierra Leone', 'SL', 'SLE'),
       (65, 'Singapore', 'SG', 'SGP'),
       (1721, 'Sint Maarten', 'SX', 'SXM'),
       (421, 'Slovakia', 'SK', 'SVK'),
       (386, 'Slovenia', 'SI', 'SVN'),
       (677, 'Solomon Islands', 'SB', 'SLB'),
       (252, 'Somalia', 'SO', 'SOM'),
       (27, 'South Africa', 'ZA', 'ZAF'),
       (82, 'South Korea', 'KR', 'KOR'),
       (211, 'South Sudan', 'SS', 'SSD'),
       (34, 'Spain', 'ES', 'ESP'),
       (94, 'Sri Lanka', 'LK', 'LKA'),
       (249, 'Sudan', 'SD', 'SDN'),
       (597, 'Suriname', 'SR', 'SUR'),
       (47, 'Svalbard and Jan Mayen', 'SJ', 'SJM'),
       (268, 'Swaziland', 'SZ', 'SWZ'),
       (46, 'Sweden', 'SE', 'SWE'),
       (41, 'Switzerland', 'CH', 'CHE'),
       (963, 'Syria', 'SY', 'SYR'),
       (886, 'Taiwan', 'TW', 'TWN'),
       (992, 'Tajikistan', 'TJ', 'TJK'),
       (255, 'Tanzania', 'TZ', 'TZA'),
       (66, 'Thailand', 'TH', 'THA'),
       (228, 'Togo', 'TG', 'TGO'),
       (690, 'Tokelau', 'TK', 'TKL'),
       (676, 'Tonga', 'TO', 'TON'),
       (1868, 'Trinidad and Tobago', 'TT', 'TTO'),
       (216, 'Tunisia', 'TN', 'TUN'),
       (90, 'Turkey', 'TR', 'TUR'),
       (993, 'Turkmenistan', 'TM', 'TKM'),
       (1649, 'Turks and Caicos Islands', 'TC', 'TCA'),
       (688, 'Tuvalu', 'TV', 'TUV'),
       (1340, 'U.S. Virgin Islands', 'VI', 'VIR'),
       (256, 'Uganda', 'UG', 'UGA'),
       (380, 'Ukraine', 'UA', 'UKR'),
       (971, 'United Arab Emirates', 'AE', 'ARE'),
       (44, 'United Kingdom', 'GB', 'GBR'),
       (1, 'United States', 'US', 'USA'),
       (598, 'Uruguay', 'UY', 'URY'),
       (998, 'Uzbekistan', 'UZ', 'UZB'),
       (678, 'Vanuatu', 'VU', 'VUT'),
       (379, 'Vatican', 'VA', 'VAT'),
       (58, 'Venezuela', 'VE', 'VEN'),
       (84, 'Vietnam', 'VN', 'VNM'),
       (681, 'Wallis and Futuna', 'WF', 'WLF'),
       (212, 'Western Sahara', 'EH', 'ESH'),
       (967, 'Yemen', 'YE', 'YEM'),
       (260, 'Zambia', 'ZM', 'ZMB'),
       (263, 'Zimbabwe', 'ZW', 'ZWE');


-- AIRPORT
insert into public.airports(airport_name, airport_code, city_name, city_code, country_id)
values ('Chhatrapati Shivaji International Airport', 'BOM', 'Mumbai', 'BOM', 95),
       ('Indira Gandhi International Airport', 'DEL', 'New Delhi', 'DEL', 95),
       ('Cochin International Airport', 'COK', 'Kochi', 'COK', 95),
       ('Sardar Vallabhbhai Patel International Airport', 'AMD', 'Ahmedabad', 'AMD', 95),
       ('Tiruchirappalli International Airport', 'TRZ', 'Tiruchirappalli', 'TRZ', 95),
       ('Tokyo International Airport - Haneda Airport', 'HND', 'Tokyo (Haneda)', 'HND', 105),
       ('Kansai International Airport', 'KIX', 'Osaka', 'KIX', 105),
       ('Narita International Airport', 'NRT', 'Tokyo (Narita)', 'NRT', 105),
       ('Chubu Centrair International Airport', 'NGO', 'Nagoya', 'NGO', 105),
       ('Fukuoka International Airport', 'FUK', 'Fukuoka', 'FUK', 105),
       ('Gimhae International Airport', 'PUS', 'Busan', 'PUS', 200),
       ('Daegu International Airport', 'TAE', 'Daegu', 'TAE', 200),
       ('Incheon International Airport', 'ICN', 'Incheon', 'ICN', 200),
       ('Kaohsiung International Airport', 'KHH', 'Kaohsiung', 'KHH', 211),
       ('Taiwan Taoyuan International Airport', 'TPE', 'Taipei', 'TPE', 211),
       ('Tainan Airport', 'TNN', 'Tainan', 'TNN', 211),
       ('Taichung International Airport', 'RMQ', 'Taichung', 'RMQ', 211),
       ('Kuala Lumpur International Airport (KLIA)', 'KUL', 'Kuala Lumpur', 'KUL', 127),
       ('Changi International Airport', 'SIN', 'Singapore', 'SIN', 193),
       ('Soekarno-Hatta International Airport', 'CGK', 'Jakarta', 'CGK', 196),
       ('Ngurah Rai International Airport (Denpasar)', 'DPS', 'Bali', 'DPS', 196),
       ('Siem Reap–Angkor International Airport', 'SAI', 'Siem Reap', 'SAI', 36),
       ('Yangon International Airport', 'RGN', 'Yangon', 'RGN', 144),
       ('Almaty International Airport', 'ALA', 'Almaty', 'ALA', 108),
       ('Nursultan Nazarbayev International Airport', 'NQZ', 'Astana', 'NQZ', 108),
       ('Vostosny International Airport', 'TAS', 'Tashkent', 'TAS', 231),
       ('Melbourne Tullamarine Airport', 'MEL', 'Melbourne', 'MEL', 13),
       ('Perth International Airport', 'PER', 'Perth', 'PER', 13),
       ('Brisbane International Airport', 'BNE', 'Brisbane', 'BNE', 13),
       ('Kingsford Smith Airport', 'SYD', 'Sydney', 'SYD', 13),
       ('Suvarnabhumi Airport', 'BKK', 'Bangkok', 'BKK', 214),
       ('Chiang Mai International Airport', 'CNX', 'Chiang Mai', 'CNX', 214),
       ('Chiang Rai International Airport', 'CEI', 'Chiang Rai', 'CEI', 214),
       ('Hat Yai International Airport', 'HDY', 'Hat Yai', 'HDY', 214),
       ('Khon Kaen Airport', 'KKC', 'Khon Kaen', 'KKC', 214),
       ('Krabi International Airport', 'KBV', 'Krabi', 'KBV', 214),
       ('Nakhon Si Thammarat Airport', 'NST', 'Nakhon Si Thammarat', 'NST', 214),
       ('Phuket International Airport', 'HKT', 'Phuket', 'HKT', 214),
       ('Surat Thani International Airport', 'URT', 'Surat Thani', 'URT', 214),
       ('Ubon Ratchathani Airport', 'UBP', 'Ubon Ratchathani', 'UBP', 214),
       ('Udon Thani International Airport', 'UTH', 'Udon Thani', 'UTH', 214),
       ('U-Tapao–Rayong–Pattaya International Airport', 'UTP', 'Rayong', 'UTP', 214),
       ('Tan Son Nhat International Airport', 'SGN', 'Ho Chi Minh City', 'SGN', 235),
       ('Noi Bai International Airport', 'HAN', 'Hanoi City', 'HAN', 235),
       ('Da Nang International Airport', 'DAD', 'Da Nang', 'DAD', 235),
       ('Phu Quoc International Airport', 'PQC', 'Phu Quoc', 'PQC', 235),
       ('Cam Ranh International Airport', 'CXR', 'Nha Trang', 'CXR', 235),
       ('Can Tho International Airport', 'VCA', 'Can Tho', 'VCA', 235),
       ('Lien Khuong International Airport', 'DLI', 'Da Lat', 'DLI', 235),
       ('Cat Bi International Airport', 'HPH', 'Hai Phong', 'HPH', 235),
       ('Phu Bai International Airport', 'HUI', 'Hue', 'HUI', 235),
       ('Van Don International Airport', 'VDO', 'Quang Ninh', 'VDO', 235),
       ('Vinh International Airport', 'VII', 'Nghe An', 'VII', 235),
       ('Buon Ma Thuot Airport', 'BMV', 'Dak Lak', 'BMV', 235),
       ('Chu Lai Airport', 'VCL', 'Chu Lai', 'VCL', 235),
       ('Dong Hoi Airport', 'VDH', 'Quang Binh', 'VDH', 235),
       ('Phu Cat Airport', 'UIH', 'Binh Dinh', 'UIH', 235),
       ('Pleiku Airport', 'PXU', 'Gia Lai', 'PXU', 235),
       ('Tho Xuan Airport', 'THD', 'Thanh Hoa', 'THD', 235),
       ('Tuy Hoa Airport', 'TBB', 'Phu Yen', 'TBB', 235),
       ('Hong Kong International Airport', 'HKG', 'Hong Kong', 'HKG', 92),
       ('Macau International Airport', 'MFM', 'Macao', 'MFM', 123),
       ('Hefei Xinqiao International Airport', 'HFE', 'Hefei', 'HFE', 44),
       ('Haikou Meilan International Airport', 'HAK', 'Haikou', 'HAK', 44),
       ('Baotou Airport', 'BAV', 'Baotou', 'BAV', 44),
       ('Harbin Taiping International Airport', 'HRB', 'Harbin', 'HRB', 44),
       ('Changsha Huanghua International Airport', 'CSX', 'Changsha', 'CSX', 44),
       ('Kunming Changshui International Airport', 'KMG', 'Kunming', 'KMG', 44),
       ('Dalian Zhoushuizi International Airport', 'DLC', 'Dalian', 'DLC', 44),
       ('Jinan Yaoqiang International Airport', 'TNA', 'Jinan', 'TNA', 44),
       ('Hangzhou Xiaoshan International Airport', 'HGH', 'Hangzhou', 'HGH', 44),
       ('Yinchuan Hedong International Airport', 'INC', 'Hedong', 'INC', 44),
       ('Baita Hohhot Baita International Airport', 'HET', 'Hohhot', 'HET', 44),
       ('Lanzhou Zhongchuan International Airport', 'LHW', 'Lanzhou Zhongchuan', 'LHW', 44),
       ('Nanjing Lukou International Airport', 'NKG', 'Nanjing', 'NKG', 44),
       ('Nantong Xingdong International Airport', 'NTG', 'Nantong', 'NTG', 44),
       ('Nanchang Changbei International Airport', 'KHN', 'Nanchang', 'KHN', 44),
       ('Dongsheng Airport', 'DSN', 'Ordos', 'DSN', 44),
       ('Yiwu Airport', 'YIW', 'Yiwu', 'YIW', 44),
       ('Nanning Wuxu International Airport', 'NNG', 'Nanning', 'NNG', 44),
       ('Ningbo Lishe International Airport', 'NGB', 'Ningbo', 'NGB', 44),
       ('Fuzhou Changle International Airport', 'FOC', 'Fuzhou', 'FOC', 44),
       ('Qingdao Liuting International Airport', 'TAO', 'Qingdao', 'TAO', 44),
       ('Guiyang Longdongbao Airport', 'KWE', 'Guiyang', 'KWE', 44),
       ('Xi''an Xianyang International Airport', 'XIY', 'Xi''an', 'SIA', 44),
       ('Shijiazhuang Zhengding International Airport', 'SJW', 'Shijiazhuang', 'SJW', 44),
       ('Taiyuan Wusu International Airport', 'TYN', 'Taiyuan', 'TYN', 44),
       ('Chengdu Shuangliu International Airport', 'CTU', 'Chengdu', 'CTU', 44),
       ('Shenyang Taoxian International Airport', 'SHE', 'Shenyang', 'SHE', 44),
       ('Tianjin Binhai International Airport', 'TSN', 'Tianjin', 'TSN', 44),
       ('Changzhou Benniu Airport', 'CZX', 'Changzhou', 'CZX', 44),
       ('Shanghai Pudong International Airport', 'PVG', 'Shanghai', 'SHA', 44),
       ('Zhengzhou Xinzheng International Airport', 'CGO', 'Zhengzhou', 'CGO', 44),
       ('Chongqing Jiangbei International Airport', 'CKG', 'Chongqing', 'CKG', 44),
       ('Zhangjiajie Hehua Airport', 'DYG', 'Zhangjiajie', 'DYG', 44),
       ('Changchun Longjia International Airport', 'CGQ', 'Changchun', 'CGQ', 44),
       ('Quanzhou Jinjiang International Airport', 'JJN', 'Quanzhou', 'JJN', 44),
       ('Sunan Shuofang International Airport', 'WUX', 'Wuxi', 'WUX', 44),
       ('Wuhan Tianhe International Airport', 'WUH', 'Wuhan', 'WUH', 44),
       ('Xuzhou Guanyin Airport', 'XUZ', 'Xuzhou', 'XUZ', 44);


--PERMISSION
INSERT INTO public.permissions (name, api_path, method, module)
VALUES ('Create a user', '/api/v1/users', 'POST', 'USERS'),
       ('Update a user', '/api/v1/users/{id}', 'PUT', 'USERS'),
       ('Delete a user', '/api/v1/users/{id}', 'DELETE', 'USERS'),
         ('Get a user by id', '/api/v1/users/{id}', 'GET', 'USERS'),
       ('Get logged in user', '/api/v1/users/logged-in', 'GET', 'USERS'),
       ('Get users with pagination', '/api/v1/users', 'GET', 'USERS'),
       ('Create a role', '/api/v1/roles', 'POST', 'ROLES'),
       ('Update a role', '/api/v1/roles/{id}', 'PUT', 'ROLES'),
       ('Delete a role', '/api/v1/roles/{id}', 'DELETE', 'ROLES'),
       ('Get a role by id', '/api/v1/roles/{id}', 'GET', 'ROLES'),
       ('Get roles with pagination', '/api/v1/roles', 'GET', 'ROLES'),
       ('Get all roles', '/api/v1/roles/all', 'GET', 'ROLES'),
       ('Create a permission', '/api/v1/permissions', 'POST', 'PERMISSIONS'),
       ('Update a permission', '/api/v1/permissions/{id}', 'PUT', 'PERMISSIONS'),
       ('Delete a permission', '/api/v1/permissions/{id}', 'DELETE', 'PERMISSIONS'),
       ('Get a permission by id', '/api/v1/permissions/{id}', 'GET', 'PERMISSIONS'),
       ('Get permissions with pagination', '/api/v1/permissions', 'GET', 'PERMISSIONS'),
       ('Get all permissions', '/api/v1/permissions/all', 'GET', 'PERMISSIONS'),
       ('Get airports with pagination', '/api/v1/airports', 'GET', 'AIRPORTS'),
       ('Get all airports', '/api/v1/airports/all', 'GET', 'AIRPORTS'),
       ('Create an airport', '/api/v1/airports', 'POST', 'AIRPORTS'),
        ('Delete an airport', '/api/v1/airports/{id}', 'DELETE', 'AIRPORTS'),
        ('Update an airport', '/api/v1/airports/{id}', 'PUT', 'AIRPORTS'),
       ('Get airplanes with pagination', '/api/v1/airplanes', 'GET', 'AIRPLANES'),
       ('Get all airplanes ', '/api/v1/airplanes/all', 'GET', 'AIRPLANES'),
       ('Create an airplane', '/api/v1/airplanes', 'POST', 'AIRPLANES'),
       ('Delete an airplane', '/api/v1/airplanes/{id}', 'DELETE', 'AIRPLANES'),
       ('Update an airplane', '/api/v1/airplanes/{id}', 'PUT', 'AIRPLANES');



--ROLE
INSERT INTO public.roles (role_name, description, active)
VALUES ('ADMIN', 'Admin thì full permissions', true);

INSERT INTO public.permission_role (permission_id, role_id)
VALUES (1, 1),
       (2, 1),
       (3, 1),
       (4, 1),
       (5, 1),
       (6, 1),
       (7, 1),
       (8, 1),
       (9, 1),
       (10, 1),
       (11, 1),
       (12, 1),
       (13, 1),
       (14, 1),
       (15, 1),
       (16, 1),
       (17, 1),
       (18, 1),
       (19, 1),
       (20,1),
        (21,1),
        (22,1),
        (23,1),
        (24,1),
        (25,1),
        (26,1),
        (27,1),
        (28,1);


--USER
INSERT INTO public.users (user_id, email, gender, first_name, last_name, password, phone_number, identity_number,
                          role_id, active, date_of_birth, country_id)
VALUES (gen_random_uuid(), 'admin@gmail.com', 'MALE', 'I am', 'ADMIN',
        '$2a$10$MEo.Zw55GDOEVwKtOnJ/TuKNrWVAjluxnWqH96ecqAKUwkFwAVkra', '0963243443', '123456789000', 1, true,
        '1999-01-01', 235);

--MODEL
INSERT INTO public.airplanes (model_name, manufacturer, max_distance, velocity, number_of_seats, overall_length,
                           wingspan, height, in_use, status)
VALUES ('Boeing 787', 'Boeing', 15750, 954, 311, 63.73, 60.93, 18.76, TRUE, 'ACTIVE'),
       ('Airbus A350', 'Airbus', 14350, 901, 323, 66.89, 64.75, 17.05, TRUE, 'ACTIVE'),
       ('Airbus A320 NEO', 'Airbus', 6300, 1005, 186, 37.57, 35.8, 11.76, FALSE, 'MAINTENANCE'),
       ('Airbus A321', 'Airbus', 5600, 950, 184, 44.51, 34.1, 11.76, TRUE, 'ACTIVE'),
       ('Boeing 737 MAX 8', 'Boeing', 6570, 842, 178, 39.5, 35.9, 12.3, TRUE, 'RETIRED'),
       ('Airbus A330-300', 'Airbus', 11650, 910, 277, 63.69, 60.3, 16.79, FALSE, 'MAINTENANCE'),
       ('Boeing 747-8', 'Boeing', 14815, 988, 410, 76.3, 68.4, 19.4, TRUE, 'ACTIVE'),
       ('Airbus A220-300', 'Airbus', 6111, 871, 160, 38.7, 35.4, 11.5, TRUE, 'RETIRED'),
       ('Boeing 767-300ER', 'Boeing', 11000, 850, 218, 54.94, 47.57, 15.75, TRUE, 'ACTIVE'),
       ('Airbus A310-300', 'Airbus', 9300, 780, 280, 46.66, 43.66, 15.85, FALSE, 'MAINTENANCE'),
       ('Boeing 757-200', 'Boeing', 5500, 850, 200, 38.06, 38.06, 13.56, TRUE, 'ACTIVE'),
       ('Boeing 787-9', 'Boeing', 14100, 926, 296, 63.0, 60.0, 17.0, TRUE, 'ACTIVE'),
       ('Airbus A350-1000', 'Airbus', 16400, 910, 410, 73.0, 64.75, 16.0, TRUE, 'ACTIVE'),
       ('Embraer E190', 'Embraer', 5000, 850, 100, 36.24, 28.7, 10.52, TRUE, 'ACTIVE'),
       ('Boeing 777-300ER', 'Boeing', 13650, 905, 396, 73.9, 64.8, 18.6, TRUE, 'ACTIVE'),
       ('Airbus A320', 'Airbus', 6100, 828, 180, 37.57, 35.8, 11.76, FALSE, 'RETIRED'),
       ('Boeing 737-900', 'Boeing', 5950, 876, 220, 42.1, 35.8, 12.3, TRUE, 'ACTIVE'),
       ('Bombardier CRJ900', 'Bombardier', 2950, 850, 90, 36.4, 24.9, 7.5, FALSE, 'MAINTENANCE'),
       ('Embraer E175', 'Embraer', 3700, 890, 88, 31.68, 28.7, 9.95, TRUE, 'ACTIVE'),
       ('Boeing 727', 'Boeing', 4000, 965, 149, 40.6, 32.9, 10.4, TRUE, 'RETIRED'),
       ('Airbus A319', 'Airbus', 6850, 828, 144, 33.84, 34.1, 11.76, FALSE, 'MAINTENANCE'),
       ('Boeing 787-10', 'Boeing', 11915, 903, 318, 68.3, 60.1, 18.0, TRUE, 'ACTIVE'),
       ('Airbus A340-600', 'Airbus', 14630, 903, 380, 75.3, 63.45, 17.2, TRUE, 'ACTIVE'),
       ('Boeing 727-200', 'Boeing', 4500, 965, 189, 46.7, 32.9, 10.4, FALSE, 'RETIRED'),
       ('Comac C919', 'Comac', 4075, 834, 158, 38.9, 35.4, 11.5, TRUE, 'ACTIVE'),
       ('Bombardier Q400', 'Bombardier', 2500, 667, 78, 32.8, 28.4, 8.3, TRUE, 'ACTIVE'),
       ('Airbus A380', 'Airbus', 15200, 1020, 555, 72.7, 79.8, 24.1, FALSE, 'RETIRED'),
       ('Boeing 737-800', 'Boeing', 5430, 842, 189, 39.5, 35.8, 12.5, TRUE, 'ACTIVE'),
       ('Embraer E170', 'Embraer', 4000, 820, 76, 29.9, 26.0, 9.85, FALSE, 'MAINTENANCE'),
       ('Airbus A310-200', 'Airbus', 8700, 800, 280, 46.66, 43.66, 15.85, FALSE, 'RETIRED'),
       ('Boeing 737 MAX 9', 'Boeing', 6570, 842, 220, 42.16, 35.92, 12.3, TRUE, 'ACTIVE'),
       ('Airbus A340-300', 'Airbus', 13800, 871, 295, 63.66, 60.3, 16.91, FALSE, 'MAINTENANCE'),
       ('Boeing 737-400', 'Boeing', 3750, 852, 188, 36.45, 28.9, 11.1, TRUE, 'RETIRED'),
       ('Airbus A380-800', 'Airbus', 15200, 1020, 544, 72.7, 79.8, 24.1, TRUE, 'ACTIVE'),
       ('Boeing 777-200LR', 'Boeing', 15400, 905, 317, 63.73, 60.9, 18.5, TRUE, 'ACTIVE'),
       ('Airbus A321neo', 'Airbus', 7400, 931, 244, 44.51, 35.8, 12.1, TRUE, 'ACTIVE'),
       ('Boeing 737 MAX 10', 'Boeing', 6110, 842, 230, 43.8, 35.9, 12.3, FALSE, 'MAINTENANCE'),
       ('Airbus A340-500', 'Airbus', 16020, 912, 372, 63.66, 60.3, 17.2, TRUE, 'ACTIVE'),
       ('Boeing 747-400', 'Boeing', 13450, 988, 416, 70.6, 64.9, 19.4, FALSE, 'RETIRED'),
       ('Airbus A321LR', 'Airbus', 7400, 931, 206, 44.51, 35.8, 12.1, TRUE, 'ACTIVE'),
       ('Embraer E195', 'Embraer', 4819, 870, 124, 38.7, 35.5, 12.0, FALSE, 'MAINTENANCE'),
       ('Boeing 777-9', 'Boeing', 13940, 905, 426, 76.5, 71.8, 19.7, TRUE, 'ACTIVE'),
       ('Airbus A330-900neo', 'Airbus', 13450, 930, 287, 63.7, 64.0, 16.8, TRUE, 'ACTIVE'),
       ('Comac ARJ21', 'Comac', 2225, 825, 90, 33.46, 27.28, 8.44, TRUE, 'ACTIVE'),
       ('Boeing 787-8', 'Boeing', 13620, 912, 242, 62.8, 60.1, 16.9, TRUE, 'ACTIVE');
